version: '3.8'

services:
  mariadb:
    image: mariadb:10.1
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beacon-db
      MYSQL_USER: mmp
      MYSQL_PASSWORD: qwerasdf
    ports:
      - "3306:3306"
    networks:
      - beacon-network

networks:
  beacon-network: