spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/beacon-db?useUnicode=true&characterEncoding=utf8mb4&useSSL=false
    username: mmp
    password: qwerasdf
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  # CORS 설정
  mvc:
    cors:
      mappings:
        "/**":
          allowed-origins: "http://localhost:3000"
          allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
          allowed-headers: "*"
          allow-credentials: true

# 디버깅 로그 설정
logging:
  level:
    org:
      springframework:
        security: DEBUG

# 세션 타임아웃 설정
server:
  servlet:
    session:
      timeout: 60m
